export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const ADD_USER = "ADD_USER";
export const ADD_ACCOUNT_BANK = "ADD_ACCOUNT_BANK";
export const ADD_MONEY = "ADD_MONEY";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const CLOSE_ACCOUNT_BANK = "CLOSE_ACCOUNT_BANK";